generate:
	@echo "Generating the project..."
	dart run build_runner build --delete-conflicting-outputs
	@echo "Project generated successfully!"

watch:
	@echo "Watching for changes..."
	dart run build_runner watch --delete-conflicting-outputs
	