name: varanasi
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  firebase_core: ^2.29.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  ui:
    path: ./packages/ui

dev_dependencies:
  flutter_flavorizr: ^2.2.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
