name: varanasi
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  common:
    path: ./packages/common
  firebase_core: ^2.29.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_settings_ui: ^3.0.1
  gap: ^3.0.1
  go_router: ^13.2.4
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  json_annotation: ^4.8.1
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.3
  random_avatar: ^0.0.8
  rxdart: ^0.27.7
  sliver_tools: ^0.2.12
  ui:
    path: ./packages/ui

dev_dependencies:
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.5.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
