// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkKLoyHz6dI1rJmf-e1ee3MH2pR4XwNjs',
    appId: '1:371448231205:android:87d03fd793f854d3ae16cc',
    messagingSenderId: '371448231205',
    projectId: 'project-varanasi-prod',
    storageBucket: 'project-varanasi-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuqfYLhMmeW11OTSLLlHR84WHLPNMBuyI',
    appId: '1:371448231205:ios:e5d4d305c3fdb7fdae16cc',
    messagingSenderId: '371448231205',
    projectId: 'project-varanasi-prod',
    storageBucket: 'project-varanasi-prod.appspot.com',
    androidClientId: '371448231205-nfvi3hie1ic2kt8ht5t1gefpjk4iq9hs.apps.googleusercontent.com',
    iosClientId: '371448231205-7inrtv982orcdou42vs3sa6gjt89bkbt.apps.googleusercontent.com',
    iosBundleId: 'dev.aryak.varanasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuqfYLhMmeW11OTSLLlHR84WHLPNMBuyI',
    appId: '1:371448231205:ios:5b7b1f561989f218ae16cc',
    messagingSenderId: '371448231205',
    projectId: 'project-varanasi-prod',
    storageBucket: 'project-varanasi-prod.appspot.com',
    androidClientId: '371448231205-nfvi3hie1ic2kt8ht5t1gefpjk4iq9hs.apps.googleusercontent.com',
    iosClientId: '371448231205-12k93spoirphl2jp56121u87h5mg7tsi.apps.googleusercontent.com',
    iosBundleId: 'dev.aryak.varanasiMobileApp.RunnerTests',
  );
}
