name: Varnasi Mobile App Build
run-name: ${{ github.actor }} pushed to "${{ github.ref_name }}" triggering production build 🚀
on:
  push:
    branches:
      - main

env:
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  Androi-App-Build:
    name: Android App Prod Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: |
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.STORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=\${{ secrets.STORE_FILE }} >> ${{env.PROPERTIES_PATH}}
      - run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/key.jks
      - run: flutter pub get
      - name: Flutter Prod Build
        run: flutter build apk --flavor production -t lib/main_production.dart
      - name: Upload Prod artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prod-release
          path: build/app/outputs/flutter-apk/app-prod-release.apk
